### ISSUE TITLE
Happy Panda Android App

### ISSUE THREAD

**Issue by xeon-zolt** [Bashmug/HappyPanda#4]
This is the overarching issue for the Happy Panda  Android Application. Please ensure that

- [x] Set up contributions guidelines [CONTRIBUTING.md]
- [x] Set up a pull request template
- [x] Set up an issue template
- [x]  Start coding for the app

Sometime in the future...
- [ ]  Set up continuous integration
